branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - 4
  - 5
  - 6.0
  - stable
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
addons:
  code_climate:
    repo_token: 96b5d8dae6e476abd5dffbe4b5a090dcce28a62bfbe6eb4898a770ac7a5744f7
after_script:
  - nyc report --reporter=text-lcov | codeclimate-test-reporter
